kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: amd64/node:12.22.0-buster@sha256:9aaa6014d1e0f35df427d994e436d50e3b517f4c832bc012eca97d70b9399185
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      repo: samuelph/universal-statuspage
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
    when:
      branch:
        - main
      event:
        - push

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: arm64v8/node:12.22.0-buster@sha256:f606dc22f45deeacd4d0ffc4723fd749f91b9fae7bc81c953127dfbdafb61481
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      repo: samuelph/universal-statuspage
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

trigger:
  branch:
    - main
  event:
    - push

# disable temporarily
#---
#kind: pipeline
#type: docker
#name: linux-arm
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#  - name: build
#    image: arm32v7/node:12.21.0-buster@sha256:e93d480d761345d85d283fba41585c6906c28d1670fa7f9581ead8aadf56e583
#    commands:
#      - npm install
#      - npm run build:ssr
#  - name: docker
#    image: plugins/docker
#    settings:
#      auto_tag: true
#      auto_tag_suffix: linux-arm
#      repo: samuelph/universal-statuspage
#      username:
#        from_secret: USERNAME
#      password:
#        from_secret: PASSWORD
#
#trigger:
#  branch:
#    - main
#  event:
#    - push

---
kind: pipeline
type: docker
name: manifest

steps:
  - name: publish
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      target: samuelph/universal-statuspage
      template: samuelph/universal-statuspage:OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
#        - linux/arm
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

depends_on:
  - linux-amd64
  - linux-arm64
#  - linux-arm

trigger:
  branch:
    - main
  event:
    - push
