kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:12.20.1-buster@sha256:ce4f3c9c90400203824d1029f068fd826e2ec64226f2109eb0745681550e5972
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      repo: samuelph/universal-statuspage
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
    when:
      branch:
        - main
      event:
        - push

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: node:12.20.1-buster@sha256:4f006d33bdf44b35d18a867043738510f60526697c7d4118ea38b334f86ae0eb
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      repo: samuelph/universal-statuspage
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: node:12.20.1-buster@sha256:37d6f1cfdef57f170dce16d72ed21c5d463bed4a6ed340c056ef91cb94e39199
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm
      repo: samuelph/universal-statuspage
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: manifest

platform:
  os: linux
  arch: arm64

steps:
  - name: publish
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      target: samuelph/universal-statuspage
      template: samuelph/universal-statuspage:OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm

trigger:
  branch:
    - main
  event:
    - push
