kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:lts-buster@sha256:205a1ee45d899e65e584030aee68d6c00357559ece80e1c82c00ac06415843c2
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      repo: samuelph/universal-statuspage
      build_args:
        - ARCH=amd64
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
    when:
      branch:
        - main
      event:
        - push

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: arm64v8/node:lts-buster@sha256:50c3e1bb740a5d2fc54287b0b648191878a06dd0d0f91d0d7c9c2f06fb908281
    commands:
      - npm install
      - npm run build:ssr
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      repo: samuelph/universal-statuspage
      build_args:
        - ARCH=amd64
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

trigger:
  branch:
    - main
  event:
    - push

# disable temporarily
#---
#kind: pipeline
#type: docker
#name: linux-arm
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#  - name: build
#    image: arm32v7/node:lts-buster@sha256:e93d480d761345d85d283fba41585c6906c28d1670fa7f9581ead8aadf56e583
#    commands:
#      - npm install
#      - npm run build:ssr
#  - name: docker
#    image: plugins/docker
#    settings:
#      auto_tag: true
#      auto_tag_suffix: linux-arm
#      repo: samuelph/universal-statuspage
#      username:
#        from_secret: USERNAME
#      password:
#        from_secret: PASSWORD
#
#trigger:
#  branch:
#    - main
#  event:
#    - push

---
kind: pipeline
type: docker
name: manifest

steps:
  - name: publish
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      target: samuelph/universal-statuspage
      template: samuelph/universal-statuspage:OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
      #        - linux/arm
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

depends_on:
  - linux-amd64
  - linux-arm64
#  - linux-arm

trigger:
  branch:
    - main
  event:
    - push
